# Generated by Django 4.1.4 on 2022-12-09 13:03

import cars.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/account'),
        ),
        migrations.AlterField(
            model_name='carsuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carsuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), cars.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='carsuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), cars.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='carsuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(9), cars.core.validators.validate_only_digits]),
        ),
    ]
