# Generated by Django 4.1.4 on 2022-12-09 13:39

import cars.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_carsuser_photo_alter_carsuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account', validators=[cars.core.validators.validate_file_max_size_1mb]),
        ),
    ]
