# Generated by Django 4.1.4 on 2022-12-09 19:56

import cars.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveSmallIntegerField(validators=[cars.core.validators.car_year_validator])),
                ('fuel', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('lpg', 'LPG'), ('cng', 'CNG'), ('electricity', 'Electricity')], max_length=11)),
                ('power', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('cimage', models.ImageField(upload_to='cars', validators=[cars.core.validators.validate_file_max_size_2mb])),
                ('description', models.TextField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='car.manufacturer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
